# Generated by Django 6.0.1 on 2026-04-28 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'Intern'), (2, 'Junior'), (3, 'Middle'), (4, 'Senior'), (5, 'Lead'), (6, 'Principal')], unique=True, verbose_name='Уровень')),
            ],
            options={
                'verbose_name': 'Грейд',
                'verbose_name_plural': 'Грейды',
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='TechStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Название')),
                ('category', models.CharField(choices=[('backend', 'Backend'), ('frontend', 'Frontend'), ('mobile', 'Mobile'), ('data', 'Data / ML'), ('devops', 'DevOps / Infra'), ('qa', 'QA'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Технология',
                'verbose_name_plural': 'Технологии / стеки',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Зарплата (₽/мес)')),
                ('hire_date', models.DateField(verbose_name='Дата найма')),
                ('termination_date', models.DateField(blank=True, null=True, verbose_name='Дата увольнения')),
                ('termination_reason', models.CharField(blank=True, choices=[('voluntary', 'По собственному желанию'), ('better_offer', 'Перешёл(шла) к конкуренту'), ('relocation', 'Переезд / релокация'), ('performance', 'Низкая эффективность'), ('layoff', 'Сокращение'), ('other', 'Другое')], max_length=20, verbose_name='Причина увольнения')),
                ('status', models.CharField(choices=[('active', 'Работает'), ('terminated', 'Уволен(а)')], default='active', max_length=20, verbose_name='Статус')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='analytics.department', verbose_name='Отдел')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='analytics.grade', verbose_name='Грейд')),
                ('tech_stacks', models.ManyToManyField(blank=True, related_name='employees', to='analytics.techstack', verbose_name='Стек технологий')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['-hire_date'],
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='Название вакансии')),
                ('salary_min', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Зарплата от')),
                ('salary_max', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Зарплата до')),
                ('opened_at', models.DateField(verbose_name='Дата открытия')),
                ('closed_at', models.DateField(blank=True, null=True, verbose_name='Дата закрытия')),
                ('status', models.CharField(choices=[('open', 'Открыта'), ('closed', 'Закрыта'), ('cancelled', 'Отменена')], default='open', max_length=20, verbose_name='Статус')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vacancies', to='analytics.department', verbose_name='Отдел')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vacancies', to='analytics.grade', verbose_name='Требуемый грейд')),
                ('hired_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacancies', to='analytics.employee', verbose_name='Нанятый сотрудник')),
                ('tech_stacks', models.ManyToManyField(blank=True, related_name='vacancies', to='analytics.techstack', verbose_name='Требуемый стек')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['status'], name='analytics_e_status_d9523e_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['hire_date'], name='analytics_e_hire_da_90ef37_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['termination_date'], name='analytics_e_termina_7100ad_idx'),
        ),
        migrations.AddIndex(
            model_name='vacancy',
            index=models.Index(fields=['status'], name='analytics_v_status_2a6246_idx'),
        ),
        migrations.AddIndex(
            model_name='vacancy',
            index=models.Index(fields=['opened_at'], name='analytics_v_opened__750c5b_idx'),
        ),
        migrations.AddIndex(
            model_name='vacancy',
            index=models.Index(fields=['closed_at'], name='analytics_v_closed__f96170_idx'),
        ),
    ]
